export enum KnowledgeRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  KNOWLEDGE_SUPERVISOR = 'KNOWLEDGE_SUPERVISOR',
  KNOWLEDGE_UPLOADER = 'KNOWLEDGE_UPLOADER',
  AUDITOR = 'AUDITOR',
  CHAT_USER = 'CHAT_USER',
}
