FROM node:20.19.5-alpine3.22

RUN apk add --no-cache openssl
RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY prisma ./prisma
RUN pnpm prisma:generate

EXPOSE 4005

CMD ["sh", "./scripts/ensure-dev-deps.sh"]
